### ISSUE TITLE
Map - downloads table paging is not working

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/EdaSubsettingService#105]
A spinner appears but the data displayed stays the same.

As seen on feature.vectorbase.org Mega-study with some filters in play - same problem with all entities tested.

I have not tested the EDA.

Further diagnosis: back end `tabular` request changes in the `reportConfig.paging.offset` parameter, but the response comes back the same

**Comment by dmfalke** [comment]
This looks like an issue with file based subsetting

**Comment by aurreco-uga** [comment]
working now


![Image](https://github.com/VEuPathDB/EdaSubsettingService/assets/16354313/ff4c04b5-d9f3-4199-a040-7556b0d221b5)
