### ISSUE TITLE
[Bug] Look into failed tabular subset previews

### ISSUE THREAD

**Issue by dmgaldi** [VEuPathDB/EdaSubsettingService#111]

**Comment by dmgaldi** [comment]
I'm not familiar with the comma syntax in a FROM clause of PLSQL, but it might be the source of the issue here?

I'm seeing:

`SELECT * FROM apidbuserdatasets.attributes_auto_20230606183330_fbXU_1_Avenir_1_cluster_subsetteddata,apidbuserdatasets.ancestors_auto_20230606183330_fbXU_1_Avenir_1_cluster_subsetteddata;`

returns 1 column, excludes two selected columns
 
`SELECT * FROM apidbuserdatasets.ancestors_auto_20230606183330_fbXU_1_Avenir_1_cluster_subsetteddata;`

returns 3 column, includes all selected columns

**Comment by dmgaldi** [comment]
The above can be disregarded. The select still fails in the latter example with column names provided.

However, it seems that quoting the field name works.

This works:
select STABLE_ID Avenir_1_cluster_subsetteddata_stable_id,
    "TEMP_Cluster_ID", stable_id
    from apidbuserdatasets.attributes_auto_20230606183330_fbXU_1_Avenir_1_cluster_subsetteddata
This doesn't:
select STABLE_ID Avenir_1_cluster_subsetteddata_stable_id,
    TEMP_Cluster_ID, stable_id
    from apidbuserdatasets.attributes_auto_20230606183330_fbXU_1_Avenir_1_cluster_subsetteddata
Note the quotes around TEMP_Cluster_ID

**Comment by aurreco-uga** [comment]
this got solved
check
https://epvb.slack.com/archives/GBDR4LDNC/p1692046929000949?thread_ts=1691772363.032109&cid=GBDR4LDNC
which leads to
https://epvb.slack.com/archives/CBEA7PQDQ/p1692284488379299?thread_ts=1692119396.134049&cid=CBEA7PQDQ
