### ISSUE TITLE
distribution endpoint numMissingCases seems wrong

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/EdaSubsettingService#15]
for umsp - weight i can see: 
"numVarValues":2343855,"numDistinctValues":1814,"numDistinctEntityRecords":4104822,"numMissingCases":0

either i dont know what numMissingCases represents, or it shouldnt be 0 here since we have fewer values than entities?

**Comment by ryanrdoherty** [comment]
Fixed.
