### ISSUE TITLE
Backend Subsetting: SCORE SM bug in Country filter (escape single quotes)

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/EdaSubsettingService#20]
Bug hit when subsetting SCORE S. mansoni Cluster Randomized Trial by **Country**

If I select **Kenya** or **Tanzania**, the filtering looks fine

1. When I select **Cote d'Ivoire**, ALL data is filtered out (there should be 75 households with data remaining)
2. When I select all countries, ALL data is filtered out (there should be 449 households with data remaining)

![image](https://user-images.githubusercontent.com/25450900/130280735-22c3b6da-c37f-48a1-8d41-0bd8b60ca064.png)

![image](https://user-images.githubusercontent.com/25450900/130280783-5a8aea00-5af2-45bd-89c9-b34dfbd53a6b.png)

**Comment by steve-fischer-200** [comment]
the subsetting service needs to clean string inputs for sql

**Comment by steve-fischer-200** [comment]
this is confirmed fixed on dave's dev site

**Comment by SheenaTomko** [comment]
This is fixed. Tried Danica's example plus filtering on some other categorical variables in other studies.
