### ISSUE TITLE
Backend: Subsetting distribution endpoint with filters can return counts for wrong entity

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/EdaSubsettingService#21]
Tested this on qa in PRISM ICEMR Cohort just now:
https://qa.clinepidb.org/ce.b19/app/workspace/analyses/DS_0ad509829e

How to reproduce:
1. create a filter in **Repeated measure**, such as by **Height**
2. go back to **Household** 
3. look at a Household categorical variable such as Sub-county - notice all the numbers are too high for the subset, and percentages over 100%
3. continuous variables (such as Household - numerical wealth) show the same issue: pink bars are showing repeated measure counts, grey bars show household counts (mouse-over will show you the numbers)

Attn: @ryanrdoherty

**Comment by danicahelb** [comment]
Paused until PRISM is reloaded, this doesn't seem to be happening with other studies


![image](https://user-images.githubusercontent.com/25450900/131577756-6ef54ea0-2cd2-4747-9e9b-d0e78a7844ee.png)

**Comment by danicahelb** [comment]
Possibly related to https://github.com/VEuPathDB/EdaSubsettingService/issues/23

**Comment by SheenaTomko** [comment]
Tested now that PRISM is reloaded. This is no longer an issue
