### ISSUE TITLE
Subsetting: distribution bar plot extends into infinity and reports nonsensical numbers

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/EdaSubsettingService#23]
for gems1a i first subset on age 0-83, and then clicked on country. i got this:
![image](https://user-images.githubusercontent.com/53306535/130713634-a19d55c9-0fea-44b3-9e4e-fd8c708684de.png)

**Comment by steve-fischer-200** [comment]
i am tentatively assigning this low cost, but that is pending full diagnosis

**Comment by SheenaTomko** [comment]
In GEMS1 as well, if you subset on weight (5.24-10.48) then look at rectal prolapse (in the same entity) you see this:
<img width="1013" alt="Screen Shot 2021-09-03 at 1 52 17 PM" src="https://user-images.githubusercontent.com/54597319/132053491-cf0d0330-8d90-4190-9f71-1e6c938b4b19.png">

**Comment by SheenaTomko** [comment]
Using that same filter at the repeated measure entity, if I look at categorical variables in the sample entity, the counts and bar charts look ok. If I look at variables in any other entity, the counts look wrong

**Comment by SheenaTomko** [comment]
Not sure if this is related or not, but in India ICEMR Cohort, I made a subset based on height (on repeated measure entity), then in the visualization tab with the histogram tool, if I tried any variable at an entity higher than repeated measure, I got a 500 error. Choosing variables at the repeated measure or sample entity returned a plot
<img width="1279" alt="Screen Shot 2021-09-03 at 3 04 24 PM" src="https://user-images.githubusercontent.com/54597319/132060183-16699734-0e37-44d3-9cb7-35dc92341d9a.png">

**Comment by steve-fischer-200** [comment]
confirmed fix in new data load

**Comment by aaronwlsong** [comment]
It looks good now, closing ticket. 

The original issue:
![image](https://user-images.githubusercontent.com/61077845/135672383-809ece0c-6721-4ade-8709-a0d81830e465.png)

The following issues are also solved. 
![image](https://user-images.githubusercontent.com/61077845/135673383-a1f1f991-d057-4697-9776-c0f8c46316d4.png)

![image](https://user-images.githubusercontent.com/61077845/135673726-d9a95616-7b2d-4499-be14-b55d14cd59a1.png)
