### ISSUE TITLE
GEMS1 filter on Participant->sex==female gives 500 error for visualisations.

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/EdaSubsettingService#25]
How to reproduce...

- GEMS1
- Go to Visualize
- make a barplot on country
- go back to subsetting and filter on `Participant->sex==female`
- go back to visualize and the barplot should now give a 500 error

Adding another Participant variable filter seems to make the visualization work again.  Very odd

**Comment by SheenaTomko** [comment]
This looks like it's been fixed by other changes. Tried Bob's method and visualization updated as expected. Tried a couple that DK said gave 500 errors and also saw no issues. Graphs updated as expected. Closing this and moving to Complete
