### ISSUE TITLE
Subsetting service: final bin of distribution histogram should maybe be inclusive of binEnd

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/EdaSubsettingService#26]
https://localhost:3000/eda-subsetting-service/studies/PRISM0001-1/entities/PCO_0000024/variables/EUPATH_0000026/distribution
```
{
	"binSpec": {
		"binWidth": 2,
		"displayRangeMax": 30,
		"displayRangeMin": 0
	},
	"filters": [],
	"valueSpec": "count"
}
```

There's one instance of the value 30 in this dataset.  The final bin returned  is
```
{
	"14": {
		"value": 0,
		"binStart": "28.0",
		"binEnd": "30.0",
		"binLabel": "[28.0,30.0)"
	}
}
```

I think perhaps it should be
```
{
	"14": {
		"value": 1,
		"binStart": "28.0",
		"binEnd": "30.0",
		"binLabel": "[28.0,30.0]"
	}
}
```
or alternatively, return an extra 30-32 bin?

Note that this isn't the default binWidth.  With the default binWidth (2.1) the 30 value is returned in the final bin 
```
{
	"14": {
		"value": 1,
		"binStart": "29.40000000000001",
		"binEnd": "31.50000000000001",
		"binLabel": "[29.40000000000001,31.50000000000001)"
	}
}
``` 

attn @ryanrdoherty

**Comment by ryanrdoherty** [comment]
Per discussion on Slack, resolution to this is:
In distribution, currently we treat displayRangeMax as an exclusive value (i.e. rows with that value are excluded from the histogram, not put in a remainder bin).  We will switch it to inclusive, but NOT change the range end of the final bin to inclusive, thus creating a remainder bin.

**Comment by ryanrdoherty** [comment]
Done.  We now add an extra bin containing values excluded by a bin whose end coincides with the range end.

**Comment by SheenaTomko** [comment]
This looks good. On integers and continuous data, if the bin width evenly divides the range, we get 1 extra bin with the max value
