### ISSUE TITLE
Fix up bin displays for Integer vars

### ISSUE THREAD

**Issue by ryanrdoherty** [VEuPathDB/EdaSubsettingService#30]
Newly implemented integer var distribution bins look the same as floating point nums (e.g. [0,3), [3,6), where the range end is not included.  Probably want to change these to e.g 0-2, 3-5 to reflect the values in the bin.  However, this could conflict with another request that we include the range end in the final bin if it is the "end" of the final bin.  In the above case, we have binSize=3 but if range is 0-6, we would have 2 bins: one for 0-2 (3 values) and one for 3-6 (4 values).  Is this ok?

**Comment by bobular** [comment]
Hi Ryan - maybe just include an extra `[6,9)` bin, as I think discussed on the other ticket, wherever that is!

**Comment by ryanrdoherty** [comment]
Yes, going to close this for now and wait for an official request.  The range syntax is well-known and can apply to both integer and floating point bins.

**Comment by SheenaTomko** [comment]
Looks like this is working nicely. I checked a few integer variables and set the bin width so it would leave a remainder of 1. The system created a new bin just for the last value
![Screen Shot 2021-10-06 at 1 55 58 PM](https://user-images.githubusercontent.com/54597319/136265660-59b1812d-6bf3-4034-8f4e-1ca23801d847.png)
