### ISSUE TITLE
Backend: Subsetting Service appears to be returning 'null' rather than '' (empty string) for missing values

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/EdaSubsettingService#31]
an ex request: 
`curl -X POST -H "Content-type: application/json" -d '{"filters":[],"outputVariableIds":["EUPATH_0000338","IAO_0000414"]}' http://localhost:8080/studies/PRISM0002-1/entities/EUPATH_0000738/tabular`

**Comment by ryanrdoherty** [comment]
Fixed.
