### ISSUE TITLE
In Java, use Long instead of Integer

### ISSUE THREAD

**Issue by steve-fischer-200** [VEuPathDB/EdaSubsettingService#34]
We need to, in general, be able to handle large numbers.  This might involve adjustments to the API and code generation system

**Comment by ryanrdoherty** [comment]
Found a way to do this using a branch of lib-jaxrs-container-build-utils.  EDA is the only project on that branch, but if we migrate others or convert to a config flag or other annotation, we could merge it to main.  For now, it will serve our purposes here in EDA-land.
