### ISSUE TITLE
Add "external" header option for tabular endpoint

### ISSUE THREAD

**Issue by ryanrdoherty** [VEuPathDB/EdaSubsettingService#44]
The tabular endpoint has both internal (merging/data services) and external (data table, download) clients.  External clients of "true" tabular (not JSON) prefer a different header format:

`“Variable display name [ID]”`

Since internal (i.e. software) clients still need the original header, we will request it via a new reportConfig property:

`headerFormat: enum [ internal, external ]`

**Comment by ryanrdoherty** [comment]
Decided to make the enum values "standard" and "display"; this is complete.

**Comment by SheenaTomko** [comment]
Discussed with Ryan. This will come up later when the downloads feature becomes available. He tested already and we would have to test manually with curl requests. Going to move to complete.
