### ISSUE TITLE
Update the column headers for the subset modal download files

### ISSUE THREAD

**Issue by SheenaTomko** [VEuPathDB/EdaSubsettingService#52]
Currently download files generated by the subset & download modal use the IRI (EUPATH_0000093, etc.) as the column header. Instead, the ClinEpiDB outreach team wants the header to be "Variable name [IRI]", for example "Sex [PATO_0000047]". If the variable has a unit, we want the header to be "Variable name (unit) [IRI]", for example "Hemoglobin (g/dL) [EUPATH_0000047]". This will match the headers in the bulk download files.

**Comment by SheenaTomko** [comment]
Looks good for a lot of variables, but also now have empty () at the end of a lot of variable labels, like for the PRISM Household repeated measure variable "Female Anopheles funestus count () [EUPATH_0000136]". Were the parentheses added for all numeric data? Because we definitely have a large proportion of numeric variables without units because they are simple counts or proportions.
@ryanrdoherty

**Comment by ryanrdoherty** [comment]
I was a little sloppy; checked for nulls but not empty strings.  Should be better now.

**Comment by SheenaTomko** [comment]
Looks great! Marking as complete
