### ISSUE TITLE
Use distinct names for the various subset results downloads

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/EdaSubsettingService#54]
Currently, the name of all subset downloaded files are `subset.txt`. @ryanrdoherty said he intends to name the files {studyId}_{entityId}_subsettedData.txt. 

in studies where we’ve changed the name of the “Community” entity, the name of the file should match the updated name (ex: “Compound” in WASHb Bangladesh)

**Comment by SheenaTomko** [comment]
Confirmed that downloads now have the names Danica specified. Ex: SCOREZAN1-1_Sample_subsettedData.txt
