### ISSUE TITLE
Remove time from date variables with no times in subset modal download files

### ISSUE THREAD

**Issue by SheenaTomko** [VEuPathDB/EdaSubsettingService#56]
In the download files made by the modal, the user can download dates. Usually (maybe always), these dates have no time associated, but the date appears as 2017-03-14T00:00:00 (ex LLINEUP "Observation date" variable). When there are no times entered, we want to strip out "T00:00:00" from the values.

**Comment by nkittur-uga** [comment]
Yup, times have been stripped. QA is complete.
