### ISSUE TITLE
Backend: include "scale" annotation

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/EdaSubsettingService#64]
The `scale` annotation property in the .owl files is not currently included in the JSON returned by the back end. EdaSubsettingService should include the `scale` annotation, so that it can be added to display labels.

The front end ticket for adding scale to display labels is: https://github.com/VEuPathDB/web-monorepo/issues/450

Edit: Danica clarifies on Slack:

“scale” (EUPATH_0001014) is annotated in the owl file for each study, following these rules:
Used to identify terms that are on the log scale or natural log scale, as opposed to on the linear scale. Study specific.
Set to “log” if data is on the log base 10 scale
Set to “log2” if data is on the log base 2 scale
Set to “ln” if data is on the natural log scale
Leave blank for: All continuous terms on the linear scale, all categorical terms, all categories

**Comment by danicahelb** [comment]
slack communication with @jbrestel:

"I don't think that will be a minor change.  It will be similar to what we do with units but we'll need to add tables and rebuild the database.  (in addition to adding all of the annotation properties).
I have a bunch of features in the mega study branch which will need to be incorporated and will also force a rebuild so we should do that at the same time (a few release cycles away)"

**Comment by danicahelb** [comment]
this ticket duplicates https://redmine.apidb.org/issues/47689

**Comment by danicahelb** [comment]
Slack convo from @dmfalke and @ryanrdoherty:

Dave Falke
  [1 hour ago](https://epvb.slack.com/archives/CBE520QUC/p1692812855386679?thread_ts=1692804174.391639&cid=CBE520QUC)
[@Ryan Doherty](https://epvb.slack.com/team/UBFCB7DLP)
 do you know if scale is being included in variable metadata, by the subsetting service?

Ryan Doherty
  [1 hour ago](https://epvb.slack.com/archives/CBE520QUC/p1692812978828689?thread_ts=1692804174.391639&cid=CBE520QUC)
Looks like it is not.  Not in the raml types anyway

**Comment by danicahelb** [comment]
"scale" (EUPATH_0001014) is annotated in the owl file for each study, following these rules:

Used to identify terms that are on the log scale or natural log scale, as opposed to on the linear scale. Study specific.

Set to “log” if data is on the log base 10 scale
Set to “log2” if data is on the log base 2 scale
Set to “ln” if data is on the natural log scale
Leave blank for: All continuous terms on the linear scale, all categorical terms, all categories

**Comment by danicahelb** [comment]
Related ticket: https://github.com/VEuPathDB/web-eda/issues/1055

**Comment by ryanrdoherty** [comment]
Column is now present in eda-rbld and that DB is configured on dev and qa stacks.  The backend code is now updated to read the value and display it in the API.  Waiting on client ticket https://github.com/VEuPathDB/web-monorepo/issues/450 to actually view in the UI.
