### ISSUE TITLE
Server 500 error in download modal

### ISSUE THREAD

**Issue by jernestmyers** [VEuPathDB/EdaSubsettingService#81]
In investigating [this issue](https://github.com/VEuPathDB/web-eda/issues/1568) wherein the download modal's table isn't rendered in real-time, I noticed a 500 error when attempting to select variables to include in the table. This issue seems to happen with certain private studies only, like West Africa ICEMR Cohort.

Error message:
"Unable to run SQL <WITH\nEUPATH_0000096 as (\n SELECT House_stable_id, Part_stable_id FROM eda.ancestors_WESTAFRICA01_1_Part\n),\nsubset AS (\n SELECT distinct EUPATH_0000096.Part_stable_id\n FROM EUPATH_0000096\n),\nwide_tabular AS (\n select rownum as r, wt.*\n from (\n select Part_stable_id, \n House_stable_id, \n OBI_0003075, \n ea.stable_id\n from eda.attributes_WESTAFRICA01_1_Part ea, eda.ancestors_WESTAFRICA01_1_Part a\n where ea.stable_id in (select * from subset)\n and ea.stable_id = a.Part_stable_id\n\n ) wt\n)\nselect Part_stable_id, House_stable_id, OBI_0003075\nfrom wide_tabular\nwhere r > 0 and r <= 10\n> with args [ ]"

**Comment by dmfalke** [comment]
@ryanrdoherty is this related to #78?

**Comment by SheenaTomko** [comment]
When qa'ing, look at https://github.com/VEuPathDB/web-eda/issues/1568 and https://github.com/VEuPathDB/EdaDataService/issues/226 for examples on clinepi and mbio, respectively
